### ISSUE TITLE
[riscv64-8u]macroAssembler_riscv.cpp:45:10: fatal error: opto/intrinsicnode.hpp: No such file or directory

### ISSUE THREAD

**Issue by sendaoYan** [sendaoYan/riscv-port-jdk8u-ysd#116]
```
+ cd build/linux-riscv64-normal-server-release/hotspot/linux_riscv_compiler2/generated
+ bash -c '/usr/bin/g++ -DLINUX -D_GNU_SOURCE -DRISCV64 -DPRODUCT -I. -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/share/vm/prims -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/share/vm -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/share/vm/precompiled -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/cpu/riscv/vm -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/os_cpu/linux_riscv/vm -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/os/linux/vm -I/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/os/posix/vm -I../generated -DHOTSPOT_RELEASE_VERSION="\"25.412-b00\"" -DHOTSPOT_BUILD_TARGET="\"product\"" -DHOTSPOT_BUILD_USER="\"yansendao\"" -DHOTSPOT_LIB_ARCH=\"riscv64\" -DHOTSPOT_VM_DISTRO="\"OpenJDK\""  -DTARGET_OS_FAMILY_linux -DTARGET_ARCH_riscv -DTARGET_ARCH_MODEL_riscv -DTARGET_OS_ARCH_linux_riscv -DTARGET_OS_ARCH_MODEL_linux_riscv64 -DTARGET_COMPILER_gcc -DINCLUDE_JFR=1 -DCOMPILER2 -DCOMPILER1 -fPIC -fno-rtti -fno-exceptions -D_REENTRANT -fcheck-new -fvisibility=hidden  -pipe -fno-strict-aliasing  -fno-omit-frame-pointer -O3  -g -DVM_LITTLE_ENDIAN -D_LP64=1 -Werror -Wpointer-arith -Wsign-compare -Wundef -Wunused-function -Wunused-value -Wformat=2 -Wreturn-type   -fstack-protector  -fno-delete-null-pointer-checks -fno-lifetime-dse -std=gnu++98 -DDTRACE_ENABLED -c -MMD -MP -MF ../generated/dependencies/macroAssembler_riscv.o.d -fpch-deps -o macroAssembler_riscv.o /home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/cpu/riscv/vm/macroAssembler_riscv.cpp'
/home/yansendao/git/riscv-port-jdk8u-ysd/hotspot/src/cpu/riscv/vm/macroAssembler_riscv.cpp:45:10: fatal error: opto/intrinsicnode.hpp: No such file or directory
   45 | #include "opto/intrinsicnode.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
[standalone.log](https://github.com/user-attachments/files/16420766/standalone.log)

**Comment by sendaoYan** [comment]
8207247: AARCH64: Enable Minimal and Client VM builds

**Comment by sendaoYan** [comment]
[JDK-8207247.patch](https://github.com/user-attachments/files/16420842/JDK-8207247.patch)

**Comment by sendaoYan** [comment]
8160534: aarch64: fails to build after 8157834

**Comment by sendaoYan** [comment]
[JDK-8160534.patch](https://github.com/user-attachments/files/16420901/JDK-8160534.patch)

**Comment by sendaoYan** [comment]
[JDK-8157834.patch](https://github.com/user-attachments/files/16420914/JDK-8157834.patch)

**Comment by sendaoYan** [comment]
[standalone.log](https://github.com/user-attachments/files/16420926/standalone.log)
[116.patch](https://github.com/user-attachments/files/16420928/116.patch)

**Comment by sendaoYan** [comment]
To github.com:sendaoYan/riscv-port-jdk8u-ysd.git
   6ea7619619e..e6803c3afef  minus-jbs8276799 -> minus-jbs8276799

**Comment by sendaoYan** [comment]
[make-gcc10-aarch64-fastdebug.log](https://github.com/user-attachments/files/16420936/make-gcc10-aarch64-fastdebug.log)
[make-gcc10-aarch64-release.log](https://github.com/user-attachments/files/16420939/make-gcc10-aarch64-release.log)
[make-gcc10-aarch64-slowdebug.log](https://github.com/user-attachments/files/16420941/make-gcc10-aarch64-slowdebug.log)
[make-gcc10-riscv64-fastdebug.log](https://github.com/user-attachments/files/16420943/make-gcc10-riscv64-fastdebug.log)
[make-gcc10-riscv64-release.log](https://github.com/user-attachments/files/16420945/make-gcc10-riscv64-release.log)
[make-gcc10-riscv64-slowdebug.log](https://github.com/user-attachments/files/16420947/make-gcc10-riscv64-slowdebug.log)
[make-gcc10-x86_64-fastdebug.log](https://github.com/user-attachments/files/16420949/make-gcc10-x86_64-fastdebug.log)
[make-gcc10-x86_64-release.log](https://github.com/user-attachments/files/16420951/make-gcc10-x86_64-release.log)
[make-gcc10-x86_64-slowdebug.log](https://github.com/user-attachments/files/16420955/make-gcc10-x86_64-slowdebug.log)
[make-gcc13-aarch64-fastdebug.log](https://github.com/user-attachments/files/16420957/make-gcc13-aarch64-fastdebug.log)
[make-gcc13-aarch64-release.log](https://github.com/user-attachments/files/16420960/make-gcc13-aarch64-release.log)
[make-gcc13-aarch64-slowdebug.log](https://github.com/user-attachments/files/16420965/make-gcc13-aarch64-slowdebug.log)
[make-gcc13-riscv64-fastdebug.log](https://github.com/user-attachments/files/16420968/make-gcc13-riscv64-fastdebug.log)
[make-gcc13-riscv64-release.log](https://github.com/user-attachments/files/16420971/make-gcc13-riscv64-release.log)
[make-gcc13-riscv64-slowdebug.log](https://github.com/user-attachments/files/16420973/make-gcc13-riscv64-slowdebug.log)
[make-gcc13-x86_64-fastdebug.log](https://github.com/user-attachments/files/16420975/make-gcc13-x86_64-fastdebug.log)
[make-gcc13-x86_64-release.log](https://github.com/user-attachments/files/16420979/make-gcc13-x86_64-release.log)
[make-gcc13-x86_64-slowdebug.log](https://github.com/user-attachments/files/16420981/make-gcc13-x86_64-slowdebug.log)
[standalone.log](https://github.com/user-attachments/files/16420982/standalone.log)

**Comment by sendaoYan** [comment]
[make-gcc10-aarch64-fastdebug.log](https://github.com/user-attachments/files/16421524/make-gcc10-aarch64-fastdebug.log)
[make-gcc10-aarch64-release.log](https://github.com/user-attachments/files/16421527/make-gcc10-aarch64-release.log)
[make-gcc10-aarch64-slowdebug.log](https://github.com/user-attachments/files/16421529/make-gcc10-aarch64-slowdebug.log)
[make-gcc10-riscv64-fastdebug.log](https://github.com/user-attachments/files/16421532/make-gcc10-riscv64-fastdebug.log)
[make-gcc10-riscv64-release.log](https://github.com/user-attachments/files/16421534/make-gcc10-riscv64-release.log)
[make-gcc10-riscv64-slowdebug.log](https://github.com/user-attachments/files/16421536/make-gcc10-riscv64-slowdebug.log)
[make-gcc10-x86_64-fastdebug.log](https://github.com/user-attachments/files/16421538/make-gcc10-x86_64-fastdebug.log)
[make-gcc10-x86_64-release.log](https://github.com/user-attachments/files/16421540/make-gcc10-x86_64-release.log)
[make-gcc10-x86_64-slowdebug.log](https://github.com/user-attachments/files/16421546/make-gcc10-x86_64-slowdebug.log)
[make-gcc13-aarch64-fastdebug.log](https://github.com/user-attachments/files/16421548/make-gcc13-aarch64-fastdebug.log)
[make-gcc13-aarch64-release.log](https://github.com/user-attachments/files/16421551/make-gcc13-aarch64-release.log)
[make-gcc13-aarch64-slowdebug.log](https://github.com/user-attachments/files/16421553/make-gcc13-aarch64-slowdebug.log)
[make-gcc13-riscv64-fastdebug.log](https://github.com/user-attachments/files/16421555/make-gcc13-riscv64-fastdebug.log)
[make-gcc13-riscv64-release.log](https://github.com/user-attachments/files/16421557/make-gcc13-riscv64-release.log)
[make-gcc13-riscv64-slowdebug.log](https://github.com/user-attachments/files/16421560/make-gcc13-riscv64-slowdebug.log)
[make-gcc13-x86_64-fastdebug.log](https://github.com/user-attachments/files/16421562/make-gcc13-x86_64-fastdebug.log)
[make-gcc13-x86_64-release.log](https://github.com/user-attachments/files/16421565/make-gcc13-x86_64-release.log)
[make-gcc13-x86_64-slowdebug.log](https://github.com/user-attachments/files/16421568/make-gcc13-x86_64-slowdebug.log)
[standalone.log](https://github.com/user-attachments/files/16421570/standalone.log)
